### PR TITLE
HW8,,

### PR DESCRIPTION
**Pull request by Alsubaie1989**

### CODE REVIEW

**Comment by jduras** [comment]
please create a pull request into jduras:students instead of into jduras:master

**Comment by Alsubaie1989** [comment]
Dear Dr.Duras

I tried but it says fail to make request, what should I do ?

Thanks

**Comment by sawssanb** [comment]
you should choose jduras  under students and your name under master, it is what I did and what dr.Jan told me to do and it works.

________________________________

**Comment by Alsubaie1989** [comment]
Yes I know how to do it but the problem it did not work, I don’t know what
is the problem
In the getkraken say it fails to make request

**Pull request closed without merging**
